### ISSUE TITLE
Metadata: define dataset title and other fields

### ISSUE THREAD

**Issue by damianooldoni** [riparias/vmm-rattenapp-occurrences#1]
How to call the dataset on GBIF? As the scope is wider than the [LIFE MICA related dataset](https://www.gbif.org/dataset/3634aee3-41d5-4aa2-8cb5-875859f62a3a), we should try to find a more comprehensive title. Also because we would like to maintain this dataset for quite a long time, even longer than the LIFE RIPARIAS project duration.

Other fields: @LienReyserhove, could you please send the link to the occurrence dataset template you have worked on? I have the one for checklists, but if I am not wrong you have a nice one for occurrences, right? Thanks in advance.

**Comment by damianooldoni** [comment]
From Dan (VMM) email:

> VMM rattenapp observations?

**Comment by peterdesmet** [comment]
Let's call it:

> Rat control occurrences collected by VMM in Flanders, Belgium
