### ISSUE TITLE
Add project metadata

### ISSUE THREAD

**Issue by damianooldoni** [riparias/vmm-rattenapp-occurrences#11]
Up to now there is no link to LIFE RIPARIAS in the metadata.
Adding project ID = `LIFE RIPARIAS` would be nice. If we do it consistently over all datasets we are going to maintain within LIFE RIPARIAS, we can easily filter on project ID to retrieve them easily.

**Comment by peterdesmet** [comment]
Can you revamp the Google doc we made for the network to one we can reuse for project?

**Comment by damianooldoni** [comment]
@LienReyserhove, @peterdesmet: the network page has been "revamped" to a project page. Actually quite easy: I change the title of the document only as the text suits perfectly a project page document.

**Comment by peterdesmet** [comment]
Right, but the fields to populate for project metadata are slightly different (e.g. ID, staff), see the generic project metadata for TrIAS: https://docs.google.com/document/d/1yR_s9NuEdMtKfrWDuV2RDL8ftPrTKEH5hDwHktCHM1M/edit#heading=h.ygz2t18tmtur

Can you adapt it to that format?

**Comment by mcoupremanne** [comment]
@damianooldoni back on this for a few minutes. I'll adapt the project metadata when you let mek now I can use the description!

**Comment by damianooldoni** [comment]
@peterdesmet: finally I found time to get back to this. Here the link to the reshaped document, ready for review:
https://docs.google.com/document/d/1SyZmiLcpFJ2AcDaDFZfnqrndwQFaUcxr3eKHy3fJKQY/edit#

**Comment by damianooldoni** [comment]
@LienReyserhove: project document is ready for being added. As this document will be used for many other datasets, could you please extra check it? @peterdesmet reviewed it but as final publisher, please give an extra 👀 !

**Comment by LienReyserhove** [comment]
Checked and added, see [the GBIF page](https://www.gbif.org/dataset/ddd51fa5-97ce-48ff-9a58-a09d7e76b103/project)
