### ISSUE TITLE
Mapping `SamplingProtocol`

### ISSUE THREAD

**Issue by damianooldoni** [riparias/vmm-rattenapp-occurrences#2]
In LIFE MICA dataset all data shared the same `samplingProtocol` value, i.e. `rat trap`.
How to map this field now? 
1. Is `rat trap` valid for all rat data in the export?
2. What should we use for plants?
3. Should we leave it empty for all other animals?

**Comment by damianooldoni** [comment]
From email of Dan (VMM):

> Sight observation? Voor dieren gaat het om sporen of effectieve waarnemingen van de soort. Voor planten is het hetzij een waarneming, hetzij een verwijdering (kolom geeft waargenomen/verwjderd).

**Comment by damianooldoni** [comment]
@LienReyserhove, @peterdesmet: which values should we use?

About animals, there is no way to distinguish traces from observations: something like `"casual observation | traces"` could be used?

About plants, eradications are mapped by `occurrenceRemarks = "eradicated"`. I would use `samplingProtocol = `"casual observation"` along the entire dataset?

**Comment by peterdesmet** [comment]
Note that we should map `eradicated` to `samplingProtocol` for this and any other dataset. Currently we don't do that:

https://github.com/riparias/vmm-rattenapp-occurrences/blob/c8ff54a656d514a8a4d51e9990458afce6c4eceb/sql/dwc_occurrence.sql#L29

Traces etc. are less important and can remain in `occurrenceRemarks`

**Comment by damianooldoni** [comment]
Thanks @peterdesmet. I will then proceed by:
1. removing `"eradicated"` from `occurrenceRemarks`
2. setting `samplingProtocol` = `"eradicated"` for removed plants
3. setting `samplingProtocol` = `"casual observation"` for all other plants and all the animals
